### ISSUE TITLE
明细发货查询导出bug

### ISSUE THREAD

**Issue by spurtAndy** [kakazuo/yimengtech#455]
华洛芙明细发货查询页面导出是一直读条
![11111111](https://cloud.githubusercontent.com/assets/19886532/18235157/e67d475a-7349-11e6-9126-030184820a4c.jpg)

**Comment by kakazuo** [comment]
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error

```
at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:366)

at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:432)

at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:311)

at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)

at org.apache.catalina.connector.Response.flushBuffer(Response.java:539)

at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:287)

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:151)

at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:870)

at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)

at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)

at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)

at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:685)

at java.lang.Thread.run(Thread.java:626)
```

这个问题是因为导出数据集太大，导出时间太长，导致客户端与服务端的链接丢失，现在增加客户端与服务器端链接的维持时间，代码已经提交，等待测试
